<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aplicação Web Interativa</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            background-color: #f4f4f9;
        }
        .container {
            text-align: center;
            width: 300px;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }
        input, button {
            margin: 10px 0;
            padding: 10px;
            width: 100%;
            font-size: 16px;
        }
        #greeting {
            font-size: 18px;
            margin-top: 20px;
            color: #333;
        }
    </style>
</head>
<body>

    <div class="container">
        <h2>Interação com JavaScript</h2>
        <!-- Campo de entrada para os números -->
        <input type="number" id="num1" placeholder="Digite o 1º número" />
        <input type="number" id="num2" placeholder="Digite o 2º número" />
        <button onclick="somarNumeros()">Somar Números</button>
        <p id="somaResultado"></p>
        
        <!-- Entrada para o nome -->
        <input type="text" id="nome" placeholder="Escreva o seu nome" />
        <button onclick="verificarNome()">Enviar Nome</button>
        <p id="greeting"></p>
    </div>

    <script>
        function somarNumeros() {
            // Obtendo os valores dos inputs e somando
            const num1 = parseInt(document.getElementById('num1').value);
            const num2 = parseInt(document.getElementById('num2').value);
            const resultado = num1 + num2;

            // Exibir o resultado da soma
            document.getElementById('somaResultado').innerText = `Resultado da soma: ${resultado}`;
        }

        // Variáveis para o nome
        const nomeCorreto = 'Gabs';
        
        function verificarNome() {
            // Obtém o valor do input
            const nomeInput = document.getElementById('nome').value;
            const greetingElement = document.getElementById('greeting');
            
            // Verifica o nome até ser igual a "Gabs"
            if (nomeInput === nomeCorreto) {
                greetingElement.innerText = 'Não sou seu bichinho de pelúcia, mas me deixa na sua cama, sua linda!';
            } else {
                greetingElement.innerText = 'Nome incorreto, tente novamente!';
            }
        }
    </script>
    
</body>
</html>
